/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.asu.bmi.dyauch.clinicalquery.ui;

import edu.asu.bmi.dyauch.clinicalquery.QueryEngine;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.index.Term;
import org.apache.lucene.index.Terms;
import org.apache.lucene.index.TermsEnum;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.BooleanClause;
import org.apache.lucene.search.BooleanQuery;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TermQuery;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.util.BytesRef;
import org.apache.lucene.util.Version;

/**
 *
 * @author David
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public BooleanQuery expandedQuery;
    private final UI self;
    public UI() {
        initComponents();
        self = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQuery = new javax.swing.JTextField();
        btnSubmitQuery = new javax.swing.JButton();
        btnExpand = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        pnlRes1 = new javax.swing.JPanel();
        btnRel1 = new javax.swing.JToggleButton();
        btnView1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtRes1 = new javax.swing.JTextArea();
        pnlRes2 = new javax.swing.JPanel();
        btnRel2 = new javax.swing.JToggleButton();
        btnView2 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtRes2 = new javax.swing.JTextArea();
        pnlRes3 = new javax.swing.JPanel();
        btnRel3 = new javax.swing.JToggleButton();
        btnView3 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtRes3 = new javax.swing.JTextArea();
        pnlRes4 = new javax.swing.JPanel();
        btnRel4 = new javax.swing.JToggleButton();
        btnView4 = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtRes4 = new javax.swing.JTextArea();
        pnlRes5 = new javax.swing.JPanel();
        btnRel5 = new javax.swing.JToggleButton();
        btnView5 = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtRes5 = new javax.swing.JTextArea();
        pnlRes6 = new javax.swing.JPanel();
        btnRel6 = new javax.swing.JToggleButton();
        btnView6 = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtRes6 = new javax.swing.JTextArea();
        pnlRes7 = new javax.swing.JPanel();
        btnRel7 = new javax.swing.JToggleButton();
        btnView7 = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtRes7 = new javax.swing.JTextArea();
        pnlRes8 = new javax.swing.JPanel();
        btnRel8 = new javax.swing.JToggleButton();
        btnView8 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        txtRes8 = new javax.swing.JTextArea();
        pnlRes9 = new javax.swing.JPanel();
        btnRel9 = new javax.swing.JToggleButton();
        btnView9 = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtRes9 = new javax.swing.JTextArea();
        pnlRes10 = new javax.swing.JPanel();
        btnRel10 = new javax.swing.JToggleButton();
        btnView10 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        txtRes10 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));
        jPanel1.setToolTipText("Query");
        jPanel1.setName(""); // NOI18N

        btnSubmitQuery.setText("Submit Query");
        btnSubmitQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitQueryActionPerformed(evt);
            }
        });

        btnExpand.setText("Expand Query");
        btnExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExpand)
                        .addGap(50, 50, 50)
                        .addComponent(btnSubmitQuery))
                    .addComponent(txtQuery, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitQuery)
                    .addComponent(btnExpand)))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setPreferredSize(new java.awt.Dimension(377, 1330));

        pnlRes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes1.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes1.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes1.setName(""); // NOI18N
        pnlRes1.setPreferredSize(new java.awt.Dimension(357, 111));

        btnRel1.setBackground(new java.awt.Color(255, 255, 255));
        btnRel1.setText("+");
        btnRel1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView1.setText("View");
        btnView1.setBorder(null);
        btnView1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView1.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView1.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView1.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes1.setColumns(20);
        txtRes1.setLineWrap(true);
        txtRes1.setRows(5);
        txtRes1.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtRes1);

        javax.swing.GroupLayout pnlRes1Layout = new javax.swing.GroupLayout(pnlRes1);
        pnlRes1.setLayout(pnlRes1Layout);
        pnlRes1Layout.setHorizontalGroup(
            pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes1Layout.setVerticalGroup(
            pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes1Layout.createSequentialGroup()
                        .addComponent(btnRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes2.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes2.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes2.setName(""); // NOI18N

        btnRel2.setBackground(new java.awt.Color(255, 255, 255));
        btnRel2.setText("+");
        btnRel2.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView2.setText("View");
        btnView2.setBorder(null);
        btnView2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView2.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView2.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView2.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes2.setColumns(20);
        txtRes2.setRows(5);
        jScrollPane13.setViewportView(txtRes2);

        javax.swing.GroupLayout pnlRes2Layout = new javax.swing.GroupLayout(pnlRes2);
        pnlRes2.setLayout(pnlRes2Layout);
        pnlRes2Layout.setHorizontalGroup(
            pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes2Layout.setVerticalGroup(
            pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes2Layout.createSequentialGroup()
                        .addComponent(btnRel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes3.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes3.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes3.setName(""); // NOI18N

        btnRel3.setBackground(new java.awt.Color(255, 255, 255));
        btnRel3.setText("+");
        btnRel3.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView3.setText("View");
        btnView3.setBorder(null);
        btnView3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView3.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView3.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView3.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes3.setColumns(20);
        txtRes3.setRows(5);
        jScrollPane14.setViewportView(txtRes3);

        javax.swing.GroupLayout pnlRes3Layout = new javax.swing.GroupLayout(pnlRes3);
        pnlRes3.setLayout(pnlRes3Layout);
        pnlRes3Layout.setHorizontalGroup(
            pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes3Layout.setVerticalGroup(
            pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes3Layout.createSequentialGroup()
                        .addComponent(btnRel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes4.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes4.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes4.setName(""); // NOI18N

        btnRel4.setBackground(new java.awt.Color(255, 255, 255));
        btnRel4.setText("+");
        btnRel4.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView4.setText("View");
        btnView4.setBorder(null);
        btnView4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView4.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView4.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView4.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes4.setColumns(20);
        txtRes4.setRows(5);
        jScrollPane15.setViewportView(txtRes4);

        javax.swing.GroupLayout pnlRes4Layout = new javax.swing.GroupLayout(pnlRes4);
        pnlRes4.setLayout(pnlRes4Layout);
        pnlRes4Layout.setHorizontalGroup(
            pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes4Layout.setVerticalGroup(
            pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes4Layout.createSequentialGroup()
                        .addComponent(btnRel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes5.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes5.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes5.setName(""); // NOI18N

        btnRel5.setBackground(new java.awt.Color(255, 255, 255));
        btnRel5.setText("+");
        btnRel5.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView5.setText("View");
        btnView5.setBorder(null);
        btnView5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView5.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView5.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView5.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes5.setColumns(20);
        txtRes5.setRows(5);
        jScrollPane16.setViewportView(txtRes5);

        javax.swing.GroupLayout pnlRes5Layout = new javax.swing.GroupLayout(pnlRes5);
        pnlRes5.setLayout(pnlRes5Layout);
        pnlRes5Layout.setHorizontalGroup(
            pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes5Layout.setVerticalGroup(
            pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes5Layout.createSequentialGroup()
                        .addComponent(btnRel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes6.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes6.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes6.setName(""); // NOI18N

        btnRel6.setBackground(new java.awt.Color(255, 255, 255));
        btnRel6.setText("+");
        btnRel6.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView6.setText("View");
        btnView6.setBorder(null);
        btnView6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView6.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView6.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView6.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes6.setColumns(20);
        txtRes6.setRows(5);
        jScrollPane17.setViewportView(txtRes6);

        javax.swing.GroupLayout pnlRes6Layout = new javax.swing.GroupLayout(pnlRes6);
        pnlRes6.setLayout(pnlRes6Layout);
        pnlRes6Layout.setHorizontalGroup(
            pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes6Layout.setVerticalGroup(
            pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes6Layout.createSequentialGroup()
                        .addComponent(btnRel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes7.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes7.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes7.setName(""); // NOI18N

        btnRel7.setBackground(new java.awt.Color(255, 255, 255));
        btnRel7.setText("+");
        btnRel7.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView7.setText("View");
        btnView7.setBorder(null);
        btnView7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView7.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView7.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView7.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes7.setColumns(20);
        txtRes7.setRows(5);
        jScrollPane18.setViewportView(txtRes7);

        javax.swing.GroupLayout pnlRes7Layout = new javax.swing.GroupLayout(pnlRes7);
        pnlRes7.setLayout(pnlRes7Layout);
        pnlRes7Layout.setHorizontalGroup(
            pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes7Layout.setVerticalGroup(
            pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes7Layout.createSequentialGroup()
                        .addComponent(btnRel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes8.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes8.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes8.setName(""); // NOI18N

        btnRel8.setBackground(new java.awt.Color(255, 255, 255));
        btnRel8.setText("+");
        btnRel8.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView8.setText("View");
        btnView8.setBorder(null);
        btnView8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView8.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView8.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView8.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes8.setColumns(20);
        txtRes8.setRows(5);
        jScrollPane19.setViewportView(txtRes8);

        javax.swing.GroupLayout pnlRes8Layout = new javax.swing.GroupLayout(pnlRes8);
        pnlRes8.setLayout(pnlRes8Layout);
        pnlRes8Layout.setHorizontalGroup(
            pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes8Layout.setVerticalGroup(
            pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes8Layout.createSequentialGroup()
                        .addComponent(btnRel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes9.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes9.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes9.setName(""); // NOI18N

        btnRel9.setBackground(new java.awt.Color(255, 255, 255));
        btnRel9.setText("+");
        btnRel9.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView9.setText("View");
        btnView9.setBorder(null);
        btnView9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView9.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView9.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView9.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes9.setColumns(20);
        txtRes9.setRows(5);
        jScrollPane20.setViewportView(txtRes9);

        javax.swing.GroupLayout pnlRes9Layout = new javax.swing.GroupLayout(pnlRes9);
        pnlRes9.setLayout(pnlRes9Layout);
        pnlRes9Layout.setHorizontalGroup(
            pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes9Layout.setVerticalGroup(
            pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes9Layout.createSequentialGroup()
                        .addComponent(btnRel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlRes10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes10.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes10.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes10.setName(""); // NOI18N

        btnRel10.setBackground(new java.awt.Color(255, 255, 255));
        btnRel10.setText("+");
        btnRel10.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView10.setText("View");
        btnView10.setBorder(null);
        btnView10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView10.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView10.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView10.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        txtRes10.setColumns(20);
        txtRes10.setRows(5);
        jScrollPane21.setViewportView(txtRes10);

        javax.swing.GroupLayout pnlRes10Layout = new javax.swing.GroupLayout(pnlRes10);
        pnlRes10.setLayout(pnlRes10Layout);
        pnlRes10Layout.setHorizontalGroup(
            pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes10Layout.setVerticalGroup(
            pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRes10Layout.createSequentialGroup()
                        .addComponent(btnRel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnView10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(pnlRes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRes10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jScrollPane1.setViewportView(jPanel2);

        jButton5.setText("Submit Feedback");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton12.setText("Done");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(46, 46, 46)
                        .addComponent(jButton12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton12)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Query");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionHandler
        System.out.println(evt.getSource().toString());
        final String text;
        if (evt.getSource() == btnView1){
            text = txtRes1.getText();
        }
        else if (evt.getSource() == btnView2){
            text = txtRes2.getText();
        }
        else if (evt.getSource() == btnView3){
            text = txtRes3.getText();
        }
        else if (evt.getSource() == btnView4){
            text = txtRes4.getText();
        }
        else if (evt.getSource() == btnView5){
            text = txtRes5.getText();
        }
        else if (evt.getSource() == btnView6){
            text = txtRes6.getText();
        }
        else if (evt.getSource() == btnView7){
            text = txtRes7.getText();
        }
        else if (evt.getSource() == btnView8){
            text = txtRes8.getText();
        }
        else if (evt.getSource() == btnView9){
            text = txtRes9.getText();
        }
        else if (evt.getSource() == btnView10){
            text = txtRes10.getText();
        }
        else {
            text = "Error";
        }
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DocView dv = new DocView(text);
                dv.setVisible(true);
            }
        });
        
    }//GEN-LAST:event_viewButtonActionHandler
    public void submitQuery(String q, QueryEngine qe){
        try {
            ScoreDoc[] sd;
            sd = qe.runQuery(qe.parseQuery(q), 10).scoreDocs;
            switch (sd.length) {
                case 10:    txtRes10.setText(qe.getDocText(qe.getDoc(sd[9])));
                case  9:    txtRes9.setText(qe.getDocText(qe.getDoc(sd[8])));
                case  8:    txtRes8.setText(qe.getDocText(qe.getDoc(sd[7])));
                case  7:    txtRes7.setText(qe.getDocText(qe.getDoc(sd[6])));
                case  6:    txtRes6.setText(qe.getDocText(qe.getDoc(sd[5])));
                case  5:    txtRes5.setText(qe.getDocText(qe.getDoc(sd[4])));
                case  4:    txtRes4.setText(qe.getDocText(qe.getDoc(sd[3])));
                case  3:    txtRes3.setText(qe.getDocText(qe.getDoc(sd[2])));
                case  2:    txtRes2.setText(qe.getDocText(qe.getDoc(sd[1])));
                case  1:    txtRes1.setText(qe.getDocText(qe.getDoc(sd[0])));
                            break;
                default:    break;
            }
            txtRes1.setCaretPosition(0);
            txtRes2.setCaretPosition(0);
            txtRes3.setCaretPosition(0);
            txtRes4.setCaretPosition(0);
            txtRes5.setCaretPosition(0);
            txtRes6.setCaretPosition(0);
            txtRes7.setCaretPosition(0);
            txtRes8.setCaretPosition(0);
            txtRes9.setCaretPosition(0);
            txtRes10.setCaretPosition(0);
        } catch (ParseException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex){
            
        }
    }
    
    public void submitQuery(BooleanQuery q, QueryEngine qe){
        try {
            ScoreDoc[] sd;
            sd = qe.runQuery(q, 10).scoreDocs;
            switch (sd.length) {
                case 10:    txtRes10.setText(qe.getDocText(qe.getDoc(sd[9])));
                case  9:    txtRes9.setText(qe.getDocText(qe.getDoc(sd[8])));
                case  8:    txtRes8.setText(qe.getDocText(qe.getDoc(sd[7])));
                case  7:    txtRes7.setText(qe.getDocText(qe.getDoc(sd[6])));
                case  6:    txtRes6.setText(qe.getDocText(qe.getDoc(sd[5])));
                case  5:    txtRes5.setText(qe.getDocText(qe.getDoc(sd[4])));
                case  4:    txtRes4.setText(qe.getDocText(qe.getDoc(sd[3])));
                case  3:    txtRes3.setText(qe.getDocText(qe.getDoc(sd[2])));
                case  2:    txtRes2.setText(qe.getDocText(qe.getDoc(sd[1])));
                case  1:    txtRes1.setText(qe.getDocText(qe.getDoc(sd[0])));
                            break;
                default:    break;
            }
            txtRes1.setCaretPosition(0);
            txtRes2.setCaretPosition(0);
            txtRes3.setCaretPosition(0);
            txtRes4.setCaretPosition(0);
            txtRes5.setCaretPosition(0);
            txtRes6.setCaretPosition(0);
            txtRes7.setCaretPosition(0);
            txtRes8.setCaretPosition(0);
            txtRes9.setCaretPosition(0);
            txtRes10.setCaretPosition(0);
        
        } catch (IOException ex){
            
        }
    }
    private void btnSubmitQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitQueryActionPerformed
        
            txtRes1.setText("");
            txtRes2.setText("");
            txtRes3.setText("");
            txtRes4.setText("");
            txtRes5.setText("");
            txtRes6.setText("");
            txtRes7.setText("");
            txtRes8.setText("");
            txtRes9.setText("");
            txtRes10.setText("");
            QueryEngine qe = QueryEngine.getInstance();    
        if (expandedQuery == null){        
            String q = txtQuery.getText();
            submitQuery(q,qe);
        } else {
            submitQuery(expandedQuery,qe);
        }
        
    }//GEN-LAST:event_btnSubmitQueryActionPerformed

    private void btnExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpandActionPerformed
        final String text = txtQuery.getText();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    SynSetChooser ssc = new SynSetChooser(text);
                    ssc.setVisible(true);
                    ssc.getUserInput(self);
                } catch (ParseException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btnExpandActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        FileWriter fw = null;
        try {
            fw = new FileWriter(new File("C:\\Users\\David\\Dropbox\\School\\BMI 591 Info Retrieval\\ClinicalQuery\\out.txt"));
            BufferedWriter bw = new BufferedWriter(fw);
            QueryEngine qe = QueryEngine.getInstance();
            ScoreDoc[] sd = null;
            if (expandedQuery == null){        
                try {
                    String q = txtQuery.getText();
                    sd = qe.runQuery(qe.parseQuery(q), 329).scoreDocs;
                } catch (ParseException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    sd = qe.runQuery(expandedQuery, 329).scoreDocs;
                } catch (IOException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            Document d;
            for (ScoreDoc doc:sd){
                try {
                    d=qe.getDoc(doc);
                    bw.write(doc.score + "\t" + d.get("path") + "\r\n");
                    
                } catch (IOException ex) {
                    Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            bw.close();
            
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (expandedQuery == null){
            try{
            expandedQuery = new BooleanQuery();
            QueryParser qp = new QueryParser(Version.LUCENE_40, "contents",new StandardAnalyzer(Version.LUCENE_40));
            Query q1 = qp.parse(txtQuery.getText());
            Query q2 = q1.rewrite(QueryEngine.getInstance().ir2);
            HashSet<Term>terms = new HashSet<Term>();
            q2.extractTerms(terms);
            for (Term t:terms){
                expandedQuery.add(new TermQuery(t),BooleanClause.Occur.SHOULD);
            }
            } catch (Exception e) {}
            }
        
        try{
        ArrayList<ScoreDoc> reldocs = new ArrayList<ScoreDoc>();
        ScoreDoc[] sd = QueryEngine.getInstance().runQuery(expandedQuery, 10).scoreDocs;
        QueryEngine qe=QueryEngine.getInstance();
        
        if (btnRel1.isSelected()){
            btnRel1.setSelected(false);
            reldocs.add(sd[0]);
        }
        if (btnRel2.isSelected()){
            btnRel2.setSelected(false);
            reldocs.add(sd[1]);
        }
        if (btnRel3.isSelected()){
            btnRel3.setSelected(false);
            reldocs.add(sd[2]);
        }
        if (btnRel4.isSelected()){
            btnRel4.setSelected(false);
            reldocs.add(sd[3]);
        }
        if (btnRel5.isSelected()){
            btnRel5.setSelected(false);
            reldocs.add(sd[4]);
        }
        if (btnRel6.isSelected()){
            btnRel6.setSelected(false);
            reldocs.add(sd[5]);
        }
        if (btnRel7.isSelected()){
            btnRel7.setSelected(false);
            reldocs.add(sd[6]);
        }
        if (btnRel8.isSelected()){
            btnRel8.setSelected(false);
            reldocs.add(sd[7]);
        }
        if (btnRel9.isSelected()){
            btnRel9.setSelected(false);
            reldocs.add(sd[8]);
        }
        if (btnRel10.isSelected()){
            btnRel10.setSelected(false);
            reldocs.add(sd[9]);
        }
        
        
        for (ScoreDoc dc:reldocs){
            Terms tvector = qe.ir2.getTermVector(dc.doc,"contents");
            TermsEnum termsEnum = tvector.iterator(null);
            BytesRef term = null;
            while ((term = termsEnum.next()) != null) {
                System.out.println(termsEnum.term().utf8ToString());
            }
        }
        }
        catch (IOException e) {System.out.println("Exception");}
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpand;
    private javax.swing.JToggleButton btnRel1;
    private javax.swing.JToggleButton btnRel10;
    private javax.swing.JToggleButton btnRel2;
    private javax.swing.JToggleButton btnRel3;
    private javax.swing.JToggleButton btnRel4;
    private javax.swing.JToggleButton btnRel5;
    private javax.swing.JToggleButton btnRel6;
    private javax.swing.JToggleButton btnRel7;
    private javax.swing.JToggleButton btnRel8;
    private javax.swing.JToggleButton btnRel9;
    private javax.swing.JButton btnSubmitQuery;
    private javax.swing.JButton btnView1;
    private javax.swing.JButton btnView10;
    private javax.swing.JButton btnView2;
    private javax.swing.JButton btnView3;
    private javax.swing.JButton btnView4;
    private javax.swing.JButton btnView5;
    private javax.swing.JButton btnView6;
    private javax.swing.JButton btnView7;
    private javax.swing.JButton btnView8;
    private javax.swing.JButton btnView9;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlRes1;
    private javax.swing.JPanel pnlRes10;
    private javax.swing.JPanel pnlRes2;
    private javax.swing.JPanel pnlRes3;
    private javax.swing.JPanel pnlRes4;
    private javax.swing.JPanel pnlRes5;
    private javax.swing.JPanel pnlRes6;
    private javax.swing.JPanel pnlRes7;
    private javax.swing.JPanel pnlRes8;
    private javax.swing.JPanel pnlRes9;
    private javax.swing.JTextField txtQuery;
    private javax.swing.JTextArea txtRes1;
    private javax.swing.JTextArea txtRes10;
    private javax.swing.JTextArea txtRes2;
    private javax.swing.JTextArea txtRes3;
    private javax.swing.JTextArea txtRes4;
    private javax.swing.JTextArea txtRes5;
    private javax.swing.JTextArea txtRes6;
    private javax.swing.JTextArea txtRes7;
    private javax.swing.JTextArea txtRes8;
    private javax.swing.JTextArea txtRes9;
    // End of variables declaration//GEN-END:variables
}
