/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.asu.bmi.dyauch.clinicalquery.ui;

/**
 *
 * @author David
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkQueryExpansion = new javax.swing.JCheckBox();
        txtQuery = new javax.swing.JTextField();
        btnSubmitQuery = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        pnlRes1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRes1 = new javax.swing.JTextArea();
        btnRel1 = new javax.swing.JToggleButton();
        btnView1 = new javax.swing.JButton();
        pnlRes2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRes2 = new javax.swing.JTextArea();
        btnRel2 = new javax.swing.JToggleButton();
        btnView2 = new javax.swing.JButton();
        pnlRes3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRes3 = new javax.swing.JTextArea();
        btnRel3 = new javax.swing.JToggleButton();
        btnView3 = new javax.swing.JButton();
        pnlRes4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtRes4 = new javax.swing.JTextArea();
        btnRel4 = new javax.swing.JToggleButton();
        btnView4 = new javax.swing.JButton();
        pnlRes5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtRes5 = new javax.swing.JTextArea();
        btnRel5 = new javax.swing.JToggleButton();
        btnView5 = new javax.swing.JButton();
        pnlRes6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtRes6 = new javax.swing.JTextArea();
        btnRel6 = new javax.swing.JToggleButton();
        btnView6 = new javax.swing.JButton();
        pnlRes7 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtRes7 = new javax.swing.JTextArea();
        btnRel7 = new javax.swing.JToggleButton();
        btnView7 = new javax.swing.JButton();
        pnlRes8 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtRes8 = new javax.swing.JTextArea();
        btnRel8 = new javax.swing.JToggleButton();
        btnView8 = new javax.swing.JButton();
        pnlRes9 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtRes9 = new javax.swing.JTextArea();
        btnRel9 = new javax.swing.JToggleButton();
        btnView9 = new javax.swing.JButton();
        pnlRes10 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtRes10 = new javax.swing.JTextArea();
        btnRel10 = new javax.swing.JToggleButton();
        btnView10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));
        jPanel1.setToolTipText("Query");
        jPanel1.setName(""); // NOI18N

        chkQueryExpansion.setText("Use Query Expansion");
        chkQueryExpansion.setName(""); // NOI18N
        chkQueryExpansion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkQueryExpansionActionPerformed(evt);
            }
        });

        btnSubmitQuery.setText("Submit Query");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtQuery))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(chkQueryExpansion)
                        .addGap(47, 47, 47)
                        .addComponent(btnSubmitQuery)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitQuery)
                    .addComponent(chkQueryExpansion)))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setPreferredSize(new java.awt.Dimension(377, 1275));

        pnlRes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes1.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes1.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes1.setName(""); // NOI18N
        pnlRes1.setPreferredSize(new java.awt.Dimension(357, 111));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes1.setColumns(20);
        txtRes1.setRows(5);
        jScrollPane2.setViewportView(txtRes1);

        btnRel1.setBackground(new java.awt.Color(255, 255, 255));
        btnRel1.setText("+");
        btnRel1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView1.setText("View");
        btnView1.setBorder(null);
        btnView1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView1.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView1.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView1.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes1Layout = new javax.swing.GroupLayout(pnlRes1);
        pnlRes1.setLayout(pnlRes1Layout);
        pnlRes1Layout.setHorizontalGroup(
            pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes1Layout.setVerticalGroup(
            pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes1Layout.createSequentialGroup()
                        .addComponent(btnRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes2.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes2.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes2.setName(""); // NOI18N

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes2.setColumns(20);
        txtRes2.setRows(5);
        jScrollPane3.setViewportView(txtRes2);

        btnRel2.setBackground(new java.awt.Color(255, 255, 255));
        btnRel2.setText("+");
        btnRel2.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView2.setText("View");
        btnView2.setBorder(null);
        btnView2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView2.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView2.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView2.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes2Layout = new javax.swing.GroupLayout(pnlRes2);
        pnlRes2.setLayout(pnlRes2Layout);
        pnlRes2Layout.setHorizontalGroup(
            pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes2Layout.setVerticalGroup(
            pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes2Layout.createSequentialGroup()
                        .addComponent(btnRel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes3.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes3.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes3.setName(""); // NOI18N

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes3.setColumns(20);
        txtRes3.setRows(5);
        jScrollPane4.setViewportView(txtRes3);

        btnRel3.setBackground(new java.awt.Color(255, 255, 255));
        btnRel3.setText("+");
        btnRel3.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView3.setText("View");
        btnView3.setBorder(null);
        btnView3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView3.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView3.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView3.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes3Layout = new javax.swing.GroupLayout(pnlRes3);
        pnlRes3.setLayout(pnlRes3Layout);
        pnlRes3Layout.setHorizontalGroup(
            pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes3Layout.setVerticalGroup(
            pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes3Layout.createSequentialGroup()
                        .addComponent(btnRel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes4.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes4.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes4.setName(""); // NOI18N

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes4.setColumns(20);
        txtRes4.setRows(5);
        jScrollPane5.setViewportView(txtRes4);

        btnRel4.setBackground(new java.awt.Color(255, 255, 255));
        btnRel4.setText("+");
        btnRel4.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView4.setText("View");
        btnView4.setBorder(null);
        btnView4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView4.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView4.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView4.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes4Layout = new javax.swing.GroupLayout(pnlRes4);
        pnlRes4.setLayout(pnlRes4Layout);
        pnlRes4Layout.setHorizontalGroup(
            pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes4Layout.setVerticalGroup(
            pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes4Layout.createSequentialGroup()
                        .addComponent(btnRel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes5.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes5.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes5.setName(""); // NOI18N

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes5.setColumns(20);
        txtRes5.setRows(5);
        jScrollPane7.setViewportView(txtRes5);

        btnRel5.setBackground(new java.awt.Color(255, 255, 255));
        btnRel5.setText("+");
        btnRel5.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView5.setText("View");
        btnView5.setBorder(null);
        btnView5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView5.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView5.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView5.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes5Layout = new javax.swing.GroupLayout(pnlRes5);
        pnlRes5.setLayout(pnlRes5Layout);
        pnlRes5Layout.setHorizontalGroup(
            pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes5Layout.setVerticalGroup(
            pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes5Layout.createSequentialGroup()
                        .addComponent(btnRel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes6.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes6.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes6.setName(""); // NOI18N

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes6.setColumns(20);
        txtRes6.setRows(5);
        jScrollPane8.setViewportView(txtRes6);

        btnRel6.setBackground(new java.awt.Color(255, 255, 255));
        btnRel6.setText("+");
        btnRel6.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView6.setText("View");
        btnView6.setBorder(null);
        btnView6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView6.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView6.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView6.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes6Layout = new javax.swing.GroupLayout(pnlRes6);
        pnlRes6.setLayout(pnlRes6Layout);
        pnlRes6Layout.setHorizontalGroup(
            pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes6Layout.setVerticalGroup(
            pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes6Layout.createSequentialGroup()
                        .addComponent(btnRel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes7.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes7.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes7.setName(""); // NOI18N

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes7.setColumns(20);
        txtRes7.setRows(5);
        jScrollPane9.setViewportView(txtRes7);

        btnRel7.setBackground(new java.awt.Color(255, 255, 255));
        btnRel7.setText("+");
        btnRel7.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView7.setText("View");
        btnView7.setBorder(null);
        btnView7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView7.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView7.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView7.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes7Layout = new javax.swing.GroupLayout(pnlRes7);
        pnlRes7.setLayout(pnlRes7Layout);
        pnlRes7Layout.setHorizontalGroup(
            pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes7Layout.setVerticalGroup(
            pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes7Layout.createSequentialGroup()
                        .addComponent(btnRel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes8.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes8.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes8.setName(""); // NOI18N

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes8.setColumns(20);
        txtRes8.setRows(5);
        jScrollPane10.setViewportView(txtRes8);

        btnRel8.setBackground(new java.awt.Color(255, 255, 255));
        btnRel8.setText("+");
        btnRel8.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView8.setText("View");
        btnView8.setBorder(null);
        btnView8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView8.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView8.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView8.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes8Layout = new javax.swing.GroupLayout(pnlRes8);
        pnlRes8.setLayout(pnlRes8Layout);
        pnlRes8Layout.setHorizontalGroup(
            pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes8Layout.setVerticalGroup(
            pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes8Layout.createSequentialGroup()
                        .addComponent(btnRel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes9.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes9.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes9.setName(""); // NOI18N

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes9.setColumns(20);
        txtRes9.setRows(5);
        jScrollPane11.setViewportView(txtRes9);

        btnRel9.setBackground(new java.awt.Color(255, 255, 255));
        btnRel9.setText("+");
        btnRel9.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView9.setText("View");
        btnView9.setBorder(null);
        btnView9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView9.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView9.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView9.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes9Layout = new javax.swing.GroupLayout(pnlRes9);
        pnlRes9.setLayout(pnlRes9Layout);
        pnlRes9Layout.setHorizontalGroup(
            pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes9Layout.setVerticalGroup(
            pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes9Layout.createSequentialGroup()
                        .addComponent(btnRel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRes10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRes10.setMaximumSize(new java.awt.Dimension(1000, 111));
        pnlRes10.setMinimumSize(new java.awt.Dimension(357, 111));
        pnlRes10.setName(""); // NOI18N

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtRes10.setColumns(20);
        txtRes10.setRows(5);
        jScrollPane12.setViewportView(txtRes10);

        btnRel10.setBackground(new java.awt.Color(255, 255, 255));
        btnRel10.setText("+");
        btnRel10.setMargin(new java.awt.Insets(2, 2, 2, 2));

        btnView10.setText("View");
        btnView10.setBorder(null);
        btnView10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnView10.setMaximumSize(new java.awt.Dimension(65, 37));
        btnView10.setMinimumSize(new java.awt.Dimension(65, 37));
        btnView10.setPreferredSize(new java.awt.Dimension(65, 37));
        btnView10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionHandler(evt);
            }
        });

        javax.swing.GroupLayout pnlRes10Layout = new javax.swing.GroupLayout(pnlRes10);
        pnlRes10.setLayout(pnlRes10Layout);
        pnlRes10Layout.setHorizontalGroup(
            pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRes10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRes10Layout.setVerticalGroup(
            pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRes10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRes10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRes10Layout.createSequentialGroup()
                        .addComponent(btnRel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRes10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRes10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jButton5.setText("Submit Feedback");

        jButton12.setText("Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(46, 46, 46)
                        .addComponent(jButton12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton12)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Query");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkQueryExpansionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkQueryExpansionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkQueryExpansionActionPerformed

    private void viewButtonActionHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionHandler
        System.out.println(evt.getSource().toString());
        if (evt.getSource() == btnView1){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocView().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_viewButtonActionHandler

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRel1;
    private javax.swing.JToggleButton btnRel10;
    private javax.swing.JToggleButton btnRel2;
    private javax.swing.JToggleButton btnRel3;
    private javax.swing.JToggleButton btnRel4;
    private javax.swing.JToggleButton btnRel5;
    private javax.swing.JToggleButton btnRel6;
    private javax.swing.JToggleButton btnRel7;
    private javax.swing.JToggleButton btnRel8;
    private javax.swing.JToggleButton btnRel9;
    private javax.swing.JButton btnSubmitQuery;
    private javax.swing.JButton btnView1;
    private javax.swing.JButton btnView10;
    private javax.swing.JButton btnView2;
    private javax.swing.JButton btnView3;
    private javax.swing.JButton btnView4;
    private javax.swing.JButton btnView5;
    private javax.swing.JButton btnView6;
    private javax.swing.JButton btnView7;
    private javax.swing.JButton btnView8;
    private javax.swing.JButton btnView9;
    private javax.swing.JCheckBox chkQueryExpansion;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlRes1;
    private javax.swing.JPanel pnlRes10;
    private javax.swing.JPanel pnlRes2;
    private javax.swing.JPanel pnlRes3;
    private javax.swing.JPanel pnlRes4;
    private javax.swing.JPanel pnlRes5;
    private javax.swing.JPanel pnlRes6;
    private javax.swing.JPanel pnlRes7;
    private javax.swing.JPanel pnlRes8;
    private javax.swing.JPanel pnlRes9;
    private javax.swing.JTextField txtQuery;
    private javax.swing.JTextArea txtRes1;
    private javax.swing.JTextArea txtRes10;
    private javax.swing.JTextArea txtRes2;
    private javax.swing.JTextArea txtRes3;
    private javax.swing.JTextArea txtRes4;
    private javax.swing.JTextArea txtRes5;
    private javax.swing.JTextArea txtRes6;
    private javax.swing.JTextArea txtRes7;
    private javax.swing.JTextArea txtRes8;
    private javax.swing.JTextArea txtRes9;
    // End of variables declaration//GEN-END:variables
}
